version: '3.3'

services:
  app:
    image: ptut-php-app:latest
    ports:
      - 80:80
    restart: always
    
  db:
    depends_on:
      - app
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - ./mongod.conf:/etc/mongod.conf.orig

        